-- Culinary Hub — Seed generado desde seed_data.json
-- Seguro re-ejecutar: ON CONFLICT DO NOTHING en todo

-- ─── CULTURAS ─────────────────────────────────────────────────────────────

INSERT INTO cultures (slug, name_es, name_en, description_es, description_en, level) VALUES
  ('mexican', 'Mexicana', 'Mexican', 'Declarada Patrimonio Cultural Inmaterial de la Humanidad por la UNESCO en 2010. Fusión de técnicas prehispánicas (nixtamalización, molcajete) con ingredientes traídos por la colonización española. El maíz, el chile y el cacao son sus tres pilares ancestrales.', 'Declared UNESCO Intangible Cultural Heritage in 2010. A fusion of pre-Hispanic techniques (nixtamalization, molcajete) with ingredients brought by Spanish colonization. Corn, chile and cacao are its three ancestral pillars.', 1),
  ('italian', 'Italiana', 'Italian', 'La cocina italiana es en realidad un mosaico de cocinas regionales profundamente distintas. El norte privilegia la mantequilla, la polenta y el risotto; el sur, el aceite de oliva, la pasta seca y el tomate. La pasta y la pizza han conquistado el mundo, pero su riqueza real está en la diversidad.', 'Italian cuisine is actually a mosaic of deeply distinct regional cuisines. The north favors butter, polenta and risotto; the south, olive oil, dried pasta and tomato. Pasta and pizza have conquered the world, but its true richness lies in its diversity.', 1),
  ('japanese', 'Japonesa', 'Japanese', 'La cocina japonesa (washoku) es Patrimonio UNESCO desde 2013. Se fundamenta en cuatro principios: respeto al ingrediente, presentación estética, variedad en un mismo menú y sensibilidad a las estaciones. El umami —el quinto sabor— fue identificado y nombrado por un científico japonés en 1908.', 'Japanese cuisine (washoku) has been UNESCO Heritage since 2013. It is based on four principles: respect for ingredients, aesthetic presentation, variety within a single meal, and sensitivity to seasons. Umami—the fifth taste—was identified and named by a Japanese scientist in 1908.', 1),
  ('spanish', 'Española', 'Spanish', 'Una de las gastronomías más diversas del mundo gracias a sus radicalmente distintos ecosistemas: el mar Cantábrico, el Mediterráneo, la meseta castellana y el Atlántico. La dieta mediterránea, reconocida por la UNESCO, tiene en España uno de sus núcleos originales. La triada del aceite, el vino y el trigo define su identidad más profunda.', 'One of the most diverse cuisines in the world thanks to its radically different ecosystems: the Cantabrian Sea, the Mediterranean, the Castilian plateau and the Atlantic. The Mediterranean diet, recognized by UNESCO, has one of its original cores in Spain. The triad of olive oil, wine and wheat defines its deepest identity.', 1),
  ('french', 'Francesa', 'French', 'La cocina francesa estableció durante siglos los estándares de la gastronomía occidental. La cuisine classique de Escoffier codificó técnicas que se enseñan en escuelas de todo el mundo. Reconocida por la UNESCO en 2010, la ''comida gastronómica de los franceses'' es un ritual social tan importante como los alimentos mismos.', 'French cuisine set the standards of Western gastronomy for centuries. Escoffier''s cuisine classique codified techniques taught in schools worldwide. Recognized by UNESCO in 2010, the ''gastronomic meal of the French'' is a social ritual as important as the food itself.', 1),
  ('moroccan', 'Marroquí', 'Moroccan', 'La cocina marroquí es el resultado de siglos de cruce entre culturas bereber, árabe, andalusí, judía y otomana. El tajín —cocción lenta en barro— y el cuscús son sus emblemas, pero la complejidad real está en el ras el hanout, una mezcla de hasta 30 especias que cada familia guarda como secreto.', 'Moroccan cuisine is the result of centuries of cultural exchange between Berber, Arab, Andalusian, Jewish and Ottoman cultures. The tagine—slow clay cooking—and couscous are its emblems, but the real complexity lies in ras el hanout, a blend of up to 30 spices that each family keeps as a secret.', 1),
  ('indian', 'India', 'Indian', 'La India no tiene una cocina: tiene docenas. Desde la cocina vegetariana jainista hasta el tandoor del Punjab, pasando por el coco y el curry de Kerala o los biryani de Hyderabad. La biodiversidad de especias india —pimienta, cardamomo, cúrcuma, comino— definió el comercio global durante milenios y provocó la exploración europea del siglo XV.', 'India does not have one cuisine: it has dozens. From Jain vegetarian cooking to Punjabi tandoor, through Kerala''s coconut and fish curry or Hyderabad''s biryani. India''s spice biodiversity—pepper, cardamom, turmeric, cumin—defined global trade for millennia and triggered European exploration in the 15th century.', 1),
  ('peruvian', 'Peruana', 'Peruvian', 'Considerada por muchos la gastronomía más biodiversa del planeta: 4.000 variedades de papa, 650 tipos de ají, 3.000 variedades de quinua. El ceviche —marinado en ácido de lima— es su plato más reconocido. La cocina nikkei (fusión peruano-japonesa) y la chifa (peruano-china) son ejemplos únicos de gastronomía de fusión generada por migración.', 'Considered by many the most biodiverse gastronomy on the planet: 4,000 varieties of potato, 650 types of chili, 3,000 varieties of quinoa. Ceviche—marinated in lime acid—is its most recognized dish. Nikkei cuisine (Peruvian-Japanese fusion) and chifa (Peruvian-Chinese) are unique examples of fusion gastronomy generated by migration.', 1),
  ('lebanese', 'Libanesa', 'Lebanese', 'La cocina libanesa es el alma de la gastronomía levantina. El mezze —decenas de pequeños platos compartidos— es su filosofía de la hospitalidad hecha comida. El hummus, el tabbouleh, el kibbeh y el falafel han trascendido fronteras para convertirse en platos universales. El uso de hierbas frescas, limón y aceite de oliva la sitúa entre las más saludables del mundo.', 'Lebanese cuisine is the soul of Levantine gastronomy. Mezze—dozens of small shared dishes—is its philosophy of hospitality made food. Hummus, tabbouleh, kibbeh and falafel have transcended borders to become universal dishes. The use of fresh herbs, lemon and olive oil places it among the healthiest in the world.', 1),
  ('greek', 'Griega', 'Greek', 'La cocina griega es una de las más antiguas de Europa y parte fundamental de la dieta mediterránea. El olivo, la vid y el trigo —la triada sagrada griega— siguen siendo sus pilares 3.000 años después. El queso feta (DOP), el yogur griego y el aceite de oliva virgen extra son sus aportaciones más exportadas.', 'Greek cuisine is one of the oldest in Europe and a fundamental part of the Mediterranean diet. The olive, vine and wheat—the Greek sacred triad—remain its pillars 3,000 years later. Feta cheese (PDO), Greek yogurt and extra virgin olive oil are its most exported contributions.', 1),
  ('chinese', 'China', 'Chinese', 'La cocina china no es una sino ocho: Cantonesa, Sichuanesa, Shandong, Jiangsu, Zhejiang, Fujian, Hunan y Anhui. Cada una con técnicas, sabores e ingredientes radicalmente distintos. La más influyente globalmente es la cantonesa (dim sum, salteados suaves); la más extrema en sabor, la sichuanesa (pimienta de Sichuan, mala).', 'Chinese cuisine is not one but eight: Cantonese, Sichuan, Shandong, Jiangsu, Zhejiang, Fujian, Hunan and Anhui. Each with radically different techniques, flavors and ingredients. The most globally influential is Cantonese (dim sum, mild stir-fries); the most extreme in flavor, Sichuan (Sichuan pepper, mala).', 1),
  ('thai', 'Tailandesa', 'Thai', 'La cocina tailandesa busca el equilibrio perfecto y simultáneo de cinco sabores: dulce, salado, ácido, amargo y picante. La leche de coco, la hierba limón, el galangal y la pasta de curry son sus elementos definitorios. La cocina real tailandesa (cuisine royale) añade una dimensión estética de presentación única en el mundo.', 'Thai cuisine seeks the perfect and simultaneous balance of five flavors: sweet, salty, sour, bitter and spicy. Coconut milk, lemongrass, galangal and curry paste are its defining elements. Royal Thai cuisine adds an aesthetic dimension of presentation unique in the world.', 1),
  ('turkish', 'Turca', 'Turkish', 'Heredera del Imperio Otomano, la cocina turca fue durante siglos la cocina de un imperio que abarcaba tres continentes. El kebab, el börek, el baklava y el yogur son invenciones turcas que hoy son universales. El desayuno turco —un ritual de horas con docenas de pequeños platos— es considerado uno de los mejores del mundo.', 'Heir to the Ottoman Empire, Turkish cuisine was for centuries the cuisine of an empire spanning three continents. Kebab, börek, baklava and yogurt are Turkish inventions that are now universal. The Turkish breakfast—a ritual of hours with dozens of small dishes—is considered one of the best in the world.', 1),
  ('ethiopian', 'Etíope', 'Ethiopian', 'La cocina etíope se distingue por el injera, un pan plano fermentado de teff que actúa simultáneamente como plato y cubierto. Sobre él se sirven los wats (guisos) y tibbs (salteados), siempre con berbere —la mezcla de especias emblemática— y se come en comunidad directamente con la mano. La prohibición del cerdo y consideraciones religiosas dan forma a toda su gastronomía.', 'Ethiopian cuisine is distinguished by injera, a fermented teff flatbread that acts simultaneously as plate and cutlery. On it are served wats (stews) and tibbs (sautés), always with berbere—the emblematic spice blend—and eaten communally directly by hand. Pork prohibition and religious considerations shape its entire gastronomy.', 1),
  ('argentinian', 'Argentina', 'Argentinian', 'La cocina argentina es inseparable del asado: un ritual social de horas alrededor del fuego que define la identidad nacional. La Pampa y su ganadería extensiva producen una carne vacuna de calidad excepcional. La fuerte inmigración italiana (pasta) y española (empanadas, tortas) se fusionó con las tradiciones gauchas para crear una gastronomía propia.', 'Argentinian cuisine is inseparable from the asado: a social ritual of hours around fire that defines national identity. The Pampas and its extensive cattle farming produce beef of exceptional quality. Strong Italian (pasta) and Spanish (empanadas, cakes) immigration merged with gaucho traditions to create a unique gastronomy.', 1),
  ('portuguese', 'Portuguesa', 'Portuguese', 'Portugal fue el primer globalizador gastronómico de la historia moderna: sus marineros llevaron el chile a Asia, la tempura a Japón y el bacalao a todo el Atlántico. El bacalhau —bacalao— tiene supuestamente 365 recetas, una por día del año. Los pastéis de nata y la cultura del café son sus aportaciones más universales.', 'Portugal was the first gastronomic globalizer in modern history: its sailors brought chili to Asia, tempura to Japan and codfish to the entire Atlantic. Bacalhau—codfish—allegedly has 365 recipes, one for each day of the year. Pastéis de nata and coffee culture are its most universal contributions.', 1),
  ('korean', 'Coreana', 'Korean', 'La cocina coreana se articula alrededor del kimchi —verduras fermentadas— y la filosofía de los banchan: docenas de pequeños acompañamientos que rodean el plato principal. La fermentación es su técnica más desarrollada: gochujang (pasta fermentada de chile), doenjang (pasta de soja fermentada) y jeotgal (mariscos fermentados) son sus umamis propios.', 'Korean cuisine revolves around kimchi—fermented vegetables—and the philosophy of banchan: dozens of small accompaniments surrounding the main dish. Fermentation is its most developed technique: gochujang (fermented chili paste), doenjang (fermented soybean paste) and jeotgal (fermented seafood) are its own umamis.', 1),
  ('vietnamese', 'Vietnamita', 'Vietnamese', 'La cocina vietnamita es quizás la más equilibrada del sudeste asiático: usa hierbas frescas con generosidad, evita los excesos de grasa y cocina con técnicas que preservan los sabores originales. El pho —caldo de buey perfumado con anís estrellado— y el bánh mì —fusión franco-vietnamita— son sus embajadores globales. La salsa de pescado (nước mắm) es su condimento universal.', 'Vietnamese cuisine is perhaps the most balanced in Southeast Asia: it uses fresh herbs generously, avoids excess fat and cooks with techniques that preserve original flavors. Pho—ox broth perfumed with star anise—and bánh mì—French-Vietnamese fusion—are its global ambassadors. Fish sauce (nước mắm) is its universal condiment.', 1),
  ('colombian', 'Colombiana', 'Colombian', 'Colombia posee una de las mayores biodiversidades del planeta, y su cocina lo refleja: entre la costa Caribe (arroz de coco, cazuela de mariscos), la costa Pacífica (el chontaduro, el borojó), los Andes (ajiaco, bandeja paisa) y la Amazonía, conviven gastronomías radicalmente distintas. El café colombiano de altura es considerado uno de los mejores del mundo.', 'Colombia has one of the greatest biodiversities on the planet, and its cuisine reflects it: between the Caribbean coast (coconut rice, seafood casserole), the Pacific coast (chontaduro, borojó), the Andes (ajiaco, bandeja paisa) and the Amazon, radically different cuisines coexist. High-altitude Colombian coffee is considered one of the best in the world.', 1),
  ('nigerian', 'Nigeriana', 'Nigerian', 'Nigeria alberga más de 250 grupos étnicos, cada uno con sus propias tradiciones culinarias. El jollof rice es su plato más conocido internacionalmente y protagonista de una legendaria rivalidad gastronómica con Ghana. El egusi (sopa de semillas de melón), el suya (pincho especiado de carne) y el puff-puff (buñuelo) son iconos de la cocina del África occidental.', 'Nigeria is home to over 250 ethnic groups, each with its own culinary traditions. Jollof rice is its most internationally known dish and protagonist of a legendary gastronomic rivalry with Ghana. Egusi (melon seed soup), suya (spiced meat skewer) and puff-puff (doughnut) are icons of West African cuisine.', 1)
ON CONFLICT (slug) DO NOTHING;

-- ─── INGREDIENTES ──────────────────────────────────────────────────────────

INSERT INTO ingredients (slug, name_es, name_en, category) VALUES
  ('olive-oil', 'Aceite de oliva', 'Olive oil', 'oils'),
  ('coconut-oil', 'Aceite de coco', 'Coconut oil', 'oils'),
  ('sesame-oil', 'Aceite de sésamo', 'Sesame oil', 'oils'),
  ('butter', 'Mantequilla', 'Butter', 'dairy'),
  ('ghee', 'Ghee', 'Ghee', 'dairy'),
  ('garlic', 'Ajo', 'Garlic', 'vegetables'),
  ('onion', 'Cebolla', 'Onion', 'vegetables'),
  ('red-onion', 'Cebolla roja', 'Red onion', 'vegetables'),
  ('tomato', 'Tomate', 'Tomato', 'vegetables'),
  ('potato', 'Patata', 'Potato', 'vegetables'),
  ('red-pepper', 'Pimiento rojo', 'Red pepper', 'vegetables'),
  ('eggplant', 'Berenjena', 'Eggplant', 'vegetables'),
  ('zucchini', 'Calabacín', 'Zucchini', 'vegetables'),
  ('carrot', 'Zanahoria', 'Carrot', 'vegetables'),
  ('spinach', 'Espinacas', 'Spinach', 'vegetables'),
  ('cabbage', 'Col', 'Cabbage', 'vegetables'),
  ('mushroom', 'Setas / Champiñón', 'Mushroom', 'vegetables'),
  ('spring-onion', 'Cebolleta', 'Spring onion', 'vegetables'),
  ('cucumber', 'Pepino', 'Cucumber', 'vegetables'),
  ('corn', 'Maíz', 'Corn', 'grains'),
  ('avocado', 'Aguacate', 'Avocado', 'fruits'),
  ('lemon', 'Limón', 'Lemon', 'fruits'),
  ('lime', 'Lima', 'Lime', 'fruits'),
  ('mango', 'Mango', 'Mango', 'fruits'),
  ('coconut', 'Coco', 'Coconut', 'fruits'),
  ('plantain', 'Plátano macho', 'Plantain', 'fruits'),
  ('olive', 'Aceituna', 'Olive', 'fruits'),
  ('chicken', 'Pollo', 'Chicken', 'meats'),
  ('beef', 'Ternera / Res', 'Beef', 'meats'),
  ('lamb', 'Cordero', 'Lamb', 'meats'),
  ('pork', 'Cerdo', 'Pork', 'meats'),
  ('cod', 'Bacalao', 'Cod', 'seafood'),
  ('salmon', 'Salmón', 'Salmon', 'seafood'),
  ('shrimp', 'Gambas / Camarones', 'Shrimp', 'seafood'),
  ('octopus', 'Pulpo', 'Octopus', 'seafood'),
  ('tuna', 'Atún', 'Tuna', 'seafood'),
  ('fish-sauce', 'Salsa de pescado', 'Fish sauce', 'condiments'),
  ('egg', 'Huevo', 'Egg', 'proteins'),
  ('rice', 'Arroz', 'Rice', 'grains'),
  ('wheat-flour', 'Harina de trigo', 'Wheat flour', 'grains'),
  ('pasta', 'Pasta', 'Pasta', 'grains'),
  ('couscous', 'Cuscús', 'Couscous', 'grains'),
  ('quinoa', 'Quinua', 'Quinoa', 'grains'),
  ('teff', 'Teff', 'Teff', 'grains'),
  ('chickpeas', 'Garbanzos', 'Chickpeas', 'legumes'),
  ('lentils', 'Lentejas', 'Lentils', 'legumes'),
  ('black-beans', 'Frijoles negros', 'Black beans', 'legumes'),
  ('white-beans', 'Judías blancas', 'White beans', 'legumes'),
  ('milk', 'Leche', 'Milk', 'dairy'),
  ('heavy-cream', 'Nata para cocinar', 'Heavy cream', 'dairy'),
  ('parmesan', 'Queso parmesano', 'Parmesan cheese', 'dairy'),
  ('feta', 'Queso feta', 'Feta cheese', 'dairy'),
  ('yogurt', 'Yogur', 'Yogurt', 'dairy'),
  ('coconut-milk', 'Leche de coco', 'Coconut milk', 'dairy'),
  ('salt', 'Sal', 'Salt', 'seasoning'),
  ('black-pepper', 'Pimienta negra', 'Black pepper', 'spices'),
  ('cumin', 'Comino', 'Cumin', 'spices'),
  ('turmeric', 'Cúrcuma', 'Turmeric', 'spices'),
  ('paprika', 'Pimentón', 'Paprika', 'spices'),
  ('saffron', 'Azafrán', 'Saffron', 'spices'),
  ('cinnamon', 'Canela', 'Cinnamon', 'spices'),
  ('cardamom', 'Cardamomo', 'Cardamom', 'spices'),
  ('chili', 'Chile / Guindilla', 'Chili pepper', 'spices'),
  ('star-anise', 'Anís estrellado', 'Star anise', 'spices'),
  ('ginger', 'Jengibre', 'Ginger', 'spices'),
  ('coriander-seed', 'Cilantro (semilla)', 'Coriander seed', 'spices'),
  ('berbere', 'Berbere', 'Berbere', 'spices'),
  ('ras-el-hanout', 'Ras el hanout', 'Ras el hanout', 'spices'),
  ('gochujang', 'Gochujang', 'Gochujang', 'spices'),
  ('parsley', 'Perejil', 'Parsley', 'herbs'),
  ('cilantro', 'Cilantro', 'Coriander / Cilantro', 'herbs'),
  ('basil', 'Albahaca', 'Basil', 'herbs'),
  ('thyme', 'Tomillo', 'Thyme', 'herbs'),
  ('rosemary', 'Romero', 'Rosemary', 'herbs'),
  ('mint', 'Menta', 'Mint', 'herbs'),
  ('lemongrass', 'Hierba limón', 'Lemongrass', 'herbs'),
  ('bay-leaf', 'Laurel', 'Bay leaf', 'herbs'),
  ('soy-sauce', 'Salsa de soja', 'Soy sauce', 'condiments'),
  ('miso', 'Pasta de miso', 'Miso paste', 'condiments'),
  ('tahini', 'Tahini', 'Tahini', 'condiments'),
  ('tomato-paste', 'Concentrado de tomate', 'Tomato paste', 'condiments'),
  ('vinegar', 'Vinagre', 'Vinegar', 'condiments'),
  ('balsamic-vinegar', 'Vinagre balsámico', 'Balsamic vinegar', 'condiments'),
  ('chicken-broth', 'Caldo de pollo', 'Chicken broth', 'condiments'),
  ('sugar', 'Azúcar', 'Sugar', 'sweeteners'),
  ('honey', 'Miel', 'Honey', 'sweeteners'),
  ('almonds', 'Almendras', 'Almonds', 'nuts'),
  ('pine-nuts', 'Piñones', 'Pine nuts', 'nuts'),
  ('peanuts', 'Cacahuetes', 'Peanuts', 'nuts'),
  ('sesame-seeds', 'Semillas de sésamo', 'Sesame seeds', 'nuts'),
  ('white-wine', 'Vino blanco', 'White wine', 'other'),
  ('red-wine', 'Vino tinto', 'Red wine', 'other'),
  ('dark-chocolate', 'Chocolate negro', 'Dark chocolate', 'other')
ON CONFLICT (slug) DO NOTHING;
